
   [build]
   functions = "./netlify/functions"
     

   [[redirects]]
     from = "/api/*"
     to = "/.netlify/functions/:splat" # This is often correct.  The most reliable way is to use the function's name in the file path.
     status = 200