[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "https://imrservicos.netlify.app"
  to = "https://imrservicos.netlify.app/.netlify/functions/server/server.mjs"
  status = 200
