[build]
  functions = "netlify/functions" # Diretório onde estão as funções serverless
  publish = "IMRNEWSITE"      # Diretório onde estão os arquivos estáticos (frontend)

[[redirects]]
  from = "/api/capture"
  to = "/.netlify/functions/capture"
  status = 200
